name: "3 Band Eq"
parameters:
- name: "Low"
  min: -18.0
  max: 18.0
  default: 0.0
  widget: vslider_tall
  group: 0
  units: dB
  
- name: "Mid"
  min: -18.0
  max: 18.0
  default: 0.0
  group: 0
  widget: vslider_tall
  units: db
  
- name: "High"
  min: -18.0
  max: 18.0
  default: 0.0
  group: 0
  widget: vslider_tall
  units: db
