name: "Delay"
transition_policy: tail
parameters:
  - name: "Delay Gain"
    type: gain
    default: -6.0
    max: 0.0
    group: 0

settings:
  - name: "Tempo"
    page: main
    default: 120
    widget: field
    min: 1
    max: 1000
    group: 1
        
  - name: "Note"
    page: main
    default: 4
    group: 2
    options:
      - name: "Whole"
        value: 1
      - name: "Half"
        value: 2
      - name: "Quarter"
        value: 4
      - name: "Eighth"
        value: 8
      - name: "Sixteenth"
        value: 16
