name: "Distortion"
parameters:
- name: "Gain"
  default: 4.0
  min: 0.0
  max: 10
  location: dist.coefficient
  
- name: "Wet Mix"
  default: 0.7
  type: mix
  max: 1.0
  
- name: "Bass Mix"
  type: mix
  default: 0.4
  max: 1.0
  
- name: "Bass Cutoff"
  location: low_pass.cutoff_frequency
  type: freq
  default: 125
  min: 20
  max: 250

settings:
  - name: "Function"
    page: main
    default: 0
    options:
      - name: "Clip"
        value: 0
      - name: "Tanh"
        value: 1
      - name: "Arctan"
        value: 2
      - name: "Fold"
        value: 3
