name: "Low End Compressor"
parameters:
- name: "Bass Ratio"
  default: 2.0
  min: 1.0
  max: 10.0
  location: bass_comp.ratio
  group: 1

- name: "Bass Threshold"
  default: -12.0
  min:   0.0
  max: -30.0
  units: db
  location: bass_comp.threshold
  group: 1

- name: "Bass Attack"
  default: 10.0
  min: 0.01
  max: 250.0
  units: ms
  location: bass_comp.attack
  group: 2

- name: "Bass Release"
  default: 200.0
  min: 0.01
  max: 250.0
  units: ms
  location: bass_comp.release
  group: 2
  
- name: "Mid Ratio"
  default: 2.0
  min: 1.0
  max: 10.0
  location: mids_comp.ratio
  group: 3

- name: "Mid Threshold"
  default: -8.0
  min:   0.0
  max: -30.0
  location: mids_comp.threshold
  units: db
  group: 3

- name: "Mid Attack"
  default: 20.0
  min: 0.01
  max: 250.0
  location: mids_comp.attack
  units: ms
  group: 4

- name: "Mid Release"
  default: 200.0
  min: 0.01
  max: 250.0
  location: mids_comp.release
  units: ms
  group: 4
