name: "Warbler"
parameters:
- name: "Center"
  default: 440.0
  min: 50.0
  max: 1500.0
  type: freq
 
- name: "Width"
  default: 0.25
  min: 0.1
  max: 1.0
 
- name: "Reactivity"
  default: 100
  min: 200.0
  max: 0.5
  units: ms
 
- name: "Sensitivity"
  default: 2.0
  min: 0.1
  max: 10.0
 
- name: "Min Rate"
  default: 0.25
  min: 0.0
  max: 1.0
 
- name: "Max Rate"
  default: 0.5
  min: 1.0
  max: 3.0
